#!/usr/bin/env bash

if [[ -z "${PROJECT_ROOT:-}" ]]; then
  printf 'render-paths: PROJECT_ROOT must be set before sourcing\n' >&2
  return 2
fi

RENDER_ROOT="$PROJECT_ROOT/renders"
RENDER_FINAL_DIR="$RENDER_ROOT/final"
RENDER_FRAMES_DIR="$RENDER_ROOT/frames"
RENDER_CONTACT_SHEETS_DIR="$RENDER_ROOT/contact-sheets"
RENDER_PREVIEWS_DIR="$RENDER_ROOT/previews"
RENDER_SMOKE_DIR="$RENDER_ROOT/smoke"
RENDER_NARRATION_DIR="$RENDER_ROOT/narration"

export RENDER_ROOT RENDER_FINAL_DIR RENDER_FRAMES_DIR
export RENDER_CONTACT_SHEETS_DIR RENDER_PREVIEWS_DIR
export RENDER_SMOKE_DIR RENDER_NARRATION_DIR
